### ISSUE TITLE
Search url of filename

### ISSUE THREAD

**Issue by zxdawn** [j08lue/pycpt#2]
For example, I want to use IR4AVHRR6.cpt.
But, there're many links on the website.
How can I get the exact url quickly?

**Comment by j08lue** [comment]
Which website are you talking about? http://soliton.vm.bytemark.co.uk/pub/cpt-city/? I did not implement any index over their colormaps so, yes, you have to find your way through their categories to your color map.

**Comment by zxdawn** [comment]
Yes, that's the website I mentioned. It's difficult to find out the exact one ;)

**Comment by j08lue** [comment]
Yes, I know. Maybe you can use Google's index of the site, since cpt-city does not have a search function. Try to google `site:http://soliton.vm.bytemark.co.uk/pub/cpt-city red` - it works well, but does not find the color map you were after.

**Comment by zxdawn** [comment]
This [website](https://geonetcast.wordpress.com/2017/06/02/geonetclass-manipulating-goes-16-data-with-python-part-v/) mentioned the color map. It's the dropbox link. Can I use your package to read local cpt file?

**Comment by j08lue** [comment]
sure. It's really old code, but it still works. See

https://github.com/j08lue/pycpt/blob/b45f720d09da79bcd567c5cbba9a554b0a7cc1d9/pycpt/load.py#L213-L223

**Comment by zxdawn** [comment]
Thanks! It works well.
